version: "3.8"
services:
  admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: medusa-admin
    environment:
      GATSBY_MEDUSA_BACKEND_URL: http://0.0.0.0:9000
      NODE_ENV: development
    ports:
      - "7001:7001"
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules

volumes:
  node_modules:
